default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] + '_development' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] + '_test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] + '_production' %>
