version: '3'

services:
    app:
        depends_on:
          - db
        build: "./build/app"
        ports:
          - "8000:8000"
        volumes:
          - "./data/app:/app"
        links:
            - db
            - redis
        env_file:
          - ./todo.env
    db:
      image: postgres:9.5
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - "./data/postgres:/var/lib/postgresql/data"
    redis:
      image: redis:latest
      volumes:
        - "./data/redis:/var/lib/redis/data"
      ports:
        - "6379:6379"
